import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import Image from "next/image";
import { motion } from "framer-motion";

const features = [
  "32–64 GPUs per rack",
  "Supports Nvidia H800, H20, H100, A100, H200 and Huawei Ascend 910B/C",
  "Fully liquid cooled, 60–140kW per rack",
  "Chip and vendor agnostic",
  "PUE as low as 1.06",
  "Developed in collaboration with AI hardware partners",
];

export default function ProductPolyrack() {
  return (
    <div>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center mb-16"
      >
        <div className="space-y-3">
          <Badge className="font-normal text-themeBlue bg-themeBlue/10 hover:bg-themeBlue/15">
            High-Energy Density, Liquid-Cooled Server Rack
          </Badge>
          <h2 className="text-4xl font-bold ">Polyrack</h2>
          <p className="text-lg text-white/70 mb-8">
            Purpose-built racks to power AI inference workloads with maximum
            efficiency and density.
          </p>
        </div>
        <div className="w-full lg:pl-40">
          <Image
            src="/polyrack.png"
            alt="Polyrack"
            width={300}
            height={300}
            className="object-contain"
          />
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.2 }}
        className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-16"
      >
        <Card className="bg-gradient-to-r from-themeBlue/5 rounded-none border border-white/10 bg-transparent overflow-hidden">
          <CardContent className="p-0">
            {/* <div className="relative h-[300px] w-full">
              <Image
                src="/polyrack.png"
                alt="Polyrack Detail"
                fill
                className="object-cover"
              />
            </div> */}
            <div className="p-6">
              <h3 className="text-xl font-semibold mb-4">
                Advanced Cooling Technology
              </h3>
              <p className="text-white/70">
                Our liquid cooling solutions are designed to handle the extreme
                heat generated by dense AI workloads, maintaining optimal
                operating temperatures while drastically reducing energy
                consumption.
              </p>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-gradient-to-r from-themeBlue/5 rounded-none border border-white/10 bg-transparent overflow-hidden">
          <CardContent className="p-0">
            {/* <div className="relative h-[300px] w-full">
              <Image
                src="/products/polyrack-interior.png"
                alt="Polyrack Interior"
                fill
                className="object-cover"
              />
            </div> */}
            <div className="p-6">
              <h3 className="text-xl font-semibold mb-4">
                Vendor Agnostic Design
              </h3>
              <p className="text-white/70">
                Our racks are designed to work with all major AI accelerators,
                giving you the flexibility to choose the hardware that best
                suits your specific workloads and requirements.
              </p>
            </div>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.4 }}
        className="bg-gradient-to-r from-themeBlue/5 to-transparent p-8 border border-white/10"
      >
        <h3 className="text-2xl font-semibold mb-6">Key Features</h3>
        <ul className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {features.map((feature, index) => (
            <motion.li
              key={index}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.4, delay: 0.6 + index * 0.1 }}
              className="flex items-start gap-3"
            >
              <span className="text-themeBlue">•</span>
              <p className="text-white/70">{feature}</p>
            </motion.li>
          ))}
        </ul>
      </motion.div>
    </div>
  );
}
